In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [2]:
import numpy as num
x = num.array([3,4,5])
y = num.array([4,9,7])
x+y

array([ 7, 13, 12])

In [3]:
# Matrices are tow dimensional araays and vectors
x  = num.array([[1,2],
                [3,4]])

x

array([[1, 2],
       [3, 4]])

In [4]:
x.ndim

2

In [5]:
x.dtype

dtype('int64')

In [6]:
num.array([[1,2],
          [3.0,2]]).dtype

dtype('float64')

In [7]:
num.array([["we",'are'],
          ["here", 'yup']]).dtype


dtype('<U4')

In [8]:
asd = num.array([[2,3], [4,5]], float)
asd

array([[2., 3.],
       [4., 5.]])

In [9]:
x.shape

(2, 2)

In [10]:
asd.shape

(2, 2)

In [14]:
q = num.array([1,2,3,4])
sum(q)

np.int64(10)

In [16]:
reshp = num.array([1,2,3,4,5,6,7,8])
reshp

reshaped = reshp.reshape(4,2)
reshaped

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
ndim
dtype
shape
sum()
reshape()
sqrt()
corrcoef()
